---
# tasks file for nginx-webserveur
- name: installer nginx
  package:
    name: nginx
    state: present

- name: demarrer nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: deploier la page d'acueil personalisé
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart nginx
